### ISSUE TITLE
Failed to load the atom-i18n package

### ISSUE THREAD

**Issue by yesther10** [liuderchi/atom-i18n#145]
[Enter steps to reproduce below:]

1. buscar el paquete atom.i18n
2. instalar el paquete.
3. mostro el siguiente error
/home/yguerra/.atom/packages/atom-i18n/lib/main.js:11
class I18N {
^^^^^
Unexpected reserved word
Hide Stack Trace
/home/yguerra/.atom/packages/atom-i18n/lib/main.js:11
class I18N {
^^^^^
SyntaxError: Unexpected reserved word
  at exports.runInThisContext (vm.js:75:16)
  at Module._compile (module.js:458:25)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:678:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:460:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

**Atom Version**: 0.188.0-d462895
**System**: linux 3.16.0-5-686-pae
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package, v0.13.3

### Stack Trace

Failed to load the atom-i18n package

```
At /home/yguerra/.atom/packages/atom-i18n/lib/main.js:11
class I18N {
^^^^^
Unexpected reserved word

/home/yguerra/.atom/packages/atom-i18n/lib/main.js:11
class I18N {
^^^^^
SyntaxError: Unexpected reserved word
  at exports.runInThisContext (vm.js:75:16)
  at Module._compile (module.js:458:25)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:678:34)
  at /usr/share/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:460:30)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -1:32.3 command-palette:toggle (atom-pane.pane.active)
     -1:20.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:20.5 core:cancel (atom-text-editor.editor.mini)
     -0:55.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-i18n, v0.13.3

# Dev
No dev packages
```

**Comment by liuderchi** [comment]
@yesther10 what's your atom version?
