### ISSUE TITLE
Uncaught TypeError: Cannot read property 'childNodes' of null

### ISSUE THREAD

**Issue by jcze9** [liuderchi/atom-i18n#166]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'childNodes' of null

```
At C:\Users\ADMIN-PC\.atom\packages\atom-i18n\lib\welcome.js:28

TypeError: Cannot read property 'childNodes' of null
    at Function.updateWelcome (/packages/atom-i18n/lib/welcome.js:28:17)
    at setTimeout (/packages/atom-i18n/lib/welcome.js:62:38)
```

### Commands

```
```

### Non-Core Packages

```
activate-stylish-mode 2.0.0 
atom-2048 3.1.0 
atom-beautify 0.32.2 
atom-file-icons 0.6.0 
atom-i18n 0.14.0 
atom-icons 0.2.2 
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
autocomplete-java 1.2.7 
autocomplete-php 0.3.7 
autocomplete-python 1.10.5 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
color-picker 2.2.5 
color-tabs 0.1.8 
emmet 2.4.3 
file-icons 2.1.18 
firacode 0.3.0 
icon-fonts 2.18.2 
intentions 1.1.5 
language-kotlin 0.5.0 
linter 2.2.0 
linter-csslint 2.0.0 
linter-gcc 0.7.1 
linter-htmlhint 1.4.0 
linter-javac 1.9.4 
linter-kotlin 0.6.0 
linter-php 1.5.1 
linter-python 3.1.2 
linter-ruby 1.2.6 
linter-spell 0.15.0 
linter-spell-javascript 0.9.0 
linter-ui-default 1.7.1 
logo-file-icons 1.13.0 
merge-conflicts 1.4.5 
minimal-icons-menu-tolls 0.5.0 
multi-cursor 2.1.5 
neon-syntax 0.3.7 
overlay-status-icons 0.1.6 
php-hyperclick 1.2.1 
php-integrator-autocomplete-plus-legacy-php56 1.0.1 
pigments 0.40.2 
python-indent 1.1.4 
python-tools 0.6.9 
quick-highlight 0.13.0 
seti-icons 1.5.4 
tron-legacy-ui 0.6.0 
```

**Comment by liuderchi** [comment]
@jcze9 thanks for reporting 🙇 
Starting finding the root causes...
