### ISSUE TITLE
Uncaught TypeError: itemSet.items is not iterable

### ISSUE THREAD

**Issue by Diamantinomc** [liuderchi/atom-i18n#193]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.16.0

### Stack Trace

Uncaught TypeError: itemSet.items is not iterable

```
At C:\Users\delar\.atom\packages\atom-i18n\lib\context-menu.js:13

TypeError: itemSet.items is not iterable
    at Function.updateContextMenu (/packages/atom-i18n/lib/context-menu.js:13:32)
    at Function.localize (/packages/atom-i18n/lib/context-menu.js:4:10)
    at I18N.delay (/packages/atom-i18n/lib/main.js:43:17)
```

### Commands

```
     -6:12.4.0 application:open-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:55.1.0 encoding-selector:show (div.line)
     -1:26.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-i18n 0.16.0 
busy-signal 1.4.3 
colorpicker 0.3.0 
emmet 2.4.3 
file-icons 2.1.22 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
```

**Comment by liuderchi** [comment]
@Diamantinomc thanks for the report 🙇

Please help provide some debug message:

- run command `window: Toggle Dev Tools`
- in dev tools console tab, paste following code, would result be `true` ?

```js
atom.contextMenu.itemSets.map(x => x.items).map(function (obj) {
  if (obj == null) { return false; }
  return typeof obj[Symbol.iterator] === 'function';
}).every(x => x)
```

**Comment by PoorPocketsMcNewHold** [comment]
Sorry for the very late up for this issue. But here's the content of it. 
![image](https://user-images.githubusercontent.com/13170204/53037576-df636b80-347a-11e9-824b-13893bedd1a4.png)
`Uncaught SyntaxError: missing ) after argument list`

**Comment by liuderchi** [comment]
@PoorPocketsMcNewHold looks like you missed final `)` when you pasted it

**Comment by PoorPocketsMcNewHold** [comment]
Missed that indeed, Sorry.
So, I've done it again, and the results is false.
```
atom.contextMenu.itemSets.map(x => x.items).map(function (obj) {
  if (obj == null) { return false; }
  return typeof obj[Symbol.iterator] === 'function';
}).every(x => x)
false
```

**Comment by PoorPocketsMcNewHold** [comment]
Again updating that issue.
I've since changed my main OS on my computer, to Ubuntu Studio 18.10, and so, reinstalled atom from fresh, on an entirely new system, not on a windows environment. 
And look at that ! Still the same issue !
The results is still false however.
