### ISSUE TITLE
Failed to activate the atom-i18n package

### ISSUE THREAD

**Issue by Senseyka0** [liuderchi/atom-i18n#221]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.18.0

### Stack Trace

Failed to activate the atom-i18n package

```
At Cannot find module './context-menu'

Error: Cannot find module './context-menu'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:145974)
    at /packages/atom-i18n/lib/main.js:5:21)
    at /packages/atom-i18n/lib/main.js:64:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:1:666612)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3027983)
    at Package.activateNow (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3016117)
    at measure (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3015895)
    at Package.measure (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3013526)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3015755)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:3015698)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:382643)
    at config.transactAsync (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:382259)
    at Config.transactAsync (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:332443)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:382209)
    at PackageManager.activate (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:11:381827)
    at t.loadState.then (~/AppData/Local/atom/app-1.35.1/resources/app/static/<embedded>:1:688022)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-i18n 0.18.0 
atom-live-server 2.3.0 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
autosave-onchange 1.5.1 
autosave-plus 0.6.0 
busy-signal 2.0.1 
color-picker 2.3.0 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.31 
flexbox-snippets 0.3.0 
html-to-css 0.2.2 
image-preview 0.4.0 
intentions 1.1.5 
minimap 4.29.9 
platformio-ide-terminal 2.9.1 
sass 0.5.0 
teletype 0.13.3 
Tern 0.8.0 
turbo-javascript 1.4.0 
```

**Comment by liuderchi** [comment]
@Senseyka0 Please help run this command on terminal for more debug info

```bash
ls ~/.atom/packages/atom-i18n/lib
```

Also, how do you install atom-i18n package?

**Comment by nashumo** [comment]
For Windows 7 x 32bits. 
I got the same issue. 
In Atom Packages, I updated the atom-i18n to a newest and it was solved.
Hope it helps.
