### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, chdir ''

### ISSUE THREAD

**Issue by LevMartus50** [liuderchi/atom-i18n#238]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.21.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, chdir ''

```
At /Users/levmartus/.atom/packages/atom-i18n/node_modules/graceful-fs/polyfills.js:20

Error: ENOENT: no such file or directory, chdir ''
    at process.chdir (/packages/atom-i18n/node_modules/graceful-fs/polyfills.js:20:9)
    at process.chdir (/app.asar/node_modules/graceful-fs/polyfills.js:21:9)
    at generateCommand (/packages/python-runner/lib/python-runner.js:69:10)
    at executePy (/packages/python-runner/lib/python-runner.js:102:12)
    at HTMLElement.pythonRunnerExecutePy (/packages/python-runner/lib/python-runner.js:143:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347598)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:718718)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:726641)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -2:07.5.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -1:45 core:paste (div.line.cursor-line)
  2x -1:42.2.0 editor:newline (input.hidden-input)
     -0:45.4.0 core:save-as (input.hidden-input)
     -0:19.4.0 script:run (input.hidden-input)
     -0:06.6.0 python-runner:executePy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-django 0.3.2 
atom-i18n 0.21.0 
atom-mac-terminal 1.0.4 
atom-python-run 0.9.7 
atom-runner 2.7.1 
atom-terminal 0.8.0 
auto-encoding 0.7.2 
autoclose-html 0.23.0 
color-picker 2.3.0 
django-atom 0.2.4 
emmet 2.4.3 
file-icons 2.1.35 
fold-lines 0.2.2 
highlight-selected 0.16.0 
indent-guide-improved 1.4.13 
linter-write-good 0.9.2 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
platformio-ide-terminal 2.9.4 
python-autopep8 0.1.3 
python-runner 1.2.1 
script 3.18.1 
simple-drag-drop-text 0.5.0 
svg-preview 0.14.0 
terminal-plus 0.14.5 
```

**Comment by liuderchi** [comment]
@LevMartus50 thanks for your report.
Just want to understand how you reproduce it.

Does this issue happen when you're dispatching command `python-runner:executePy` ?
