### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LyaKich** [liuderchi/atom-i18n#286]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: 'simplified-russian-menu' package vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'sectionHeadings' of undefined

```
At C:\Users\lyaki\.atom\packages\simplified-russian-menu\tools\settings.coffee:85

TypeError: Cannot read property 'sectionHeadings' of undefined
    at applySectionHeadings (/packages/simplified-russian-menu/tools/settings.coffee:85:3)
    at HTMLAnchorElement.applyInstallPanelOnSwitch (/packages/simplified-russian-menu/tools/settings.coffee:68:3)
    at Function.loadAllSettingsPanels (/packages/atom-i18n/lib/preferences.js:67:10)
    at Function.delaySettings (/packages/atom-i18n/lib/preferences.js:19:12)
    at /packages/atom-i18n/lib/preferences.js:106:27
```

### Commands

```
     -3:51.2.0 github:toggle-github-tab (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:36.6.0 core:paste (div.line)
```

### Non-Core Packages

```
atom-i18n 0.24.0 
```

**Comment by polynoman** [comment]
Hey, if I am correct, this issue is caused by the 'simplified-russian-menu' package. It has been reported a number of times there: 
https://github.com/CappuccinoRU/atom-simplified-russian-menu/issues 

You read the stack trace from the bottom to the top, and at the top is where the error happened, which is the other package.
