### ISSUE TITLE
Failed to activate the atom-i18n package

### ISSUE THREAD

**Issue by laurensbrand** [liuderchi/atom-i18n#57]
[Enter steps to reproduce:]

1. I believe I followed the instructions "Steps to Contribute" because I would like to contribute for the Dutch language. Did the fork, did the clone and created a branch for 'nl'.
2. Enabled dev mode.

This is all very new to me so please bare with me if I did forget a step. If you could help me get started then I will see to it that there is a Dutch version asap.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-i18n](https://github.com/liuderchi/atom-i18n) package 0.7.0

### Stack Trace

Failed to activate the atom-i18n package

```
At Cannot find module 'cson'

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-i18n/lib/main.coffee:2:8)
    at /packages/atom-i18n/lib/main.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:812:28
```

### Commands

```
```

### Non-Core Packages

```
atom-i18n 0.7.0 
cson 2.0.1 
default-language 0.3.0 
```

**Comment by laurensbrand** [comment]
I issued the command npm install --save cson in the folder /Users/laurensbrand/.atom/packages which
enabled the node_modules community package.

I then went to the folder /Users/laurensbrand/.atom/packages/node_modules/cson and issued the command apm link which enabled the cson 4.0.0 community package.

But the atom-i18n package still it complains that it can not module cson.
 
![schermafbeelding 2017-03-15 om 08 28 16](https://cloud.githubusercontent.com/assets/25944955/23937779/7fc73132-0959-11e7-807e-84acc4743d2d.png)

**Comment by laurensbrand** [comment]
Figured it out did the installation of the node modules in the wrong directory. Translating now :-)

**Comment by liuderchi** [comment]
@laurensbrand Thanks for translating Dutch!
Maybe I can add instruction `npm install` to the guide to make it more complete : )

**Comment by ziyaddin** [comment]
@liuderchi I have the same issue. I think I have installed node_modules to the currect directory (main directory of the repo).

**Comment by liuderchi** [comment]
@ziyaddin Does your result of 
```
ls -lh /home/ziyaddin/github/atom-i18n/node_modules
```
look correct?

If the answer is no, please provide your steps starting from *git cloning*, thank you.

**Comment by ziyaddin** [comment]
@liuderchi yes, it looks correct. Here is the result:
```
total 816K
drwxrwxr-x  5 ziyaddin ziyaddin 4,0K Mar 28 22:18 acorn
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 acorn-jsx
drwxrwxr-x  5 ziyaddin ziyaddin 4,0K Mar 28 22:18 ajv
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 ajv-keywords
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 ansi-escapes
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 ansi-regex
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 ansi-styles
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 argparse
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 array-union
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 array-uniq
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 arrify
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 assertion-error
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 babel-code-frame
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 balanced-match
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 brace-expansion
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 browser-stdout
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 buffer-shims
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 builtin-modules
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 caller-path
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 callsites
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 camelcase
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 chai
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 chalk
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 circular-json
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 cli-cursor
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 cliui
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 cli-width
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 co
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 code-point-at
drwxrwxr-x  6 ziyaddin ziyaddin 4,0K Mar 28 22:18 coffeelint
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 coffee-script
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 commander
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 concat-map
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 concat-stream
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 core-util-is
drwxrwxr-x  5 ziyaddin ziyaddin 4,0K Mar 28 22:18 cson
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 cson-parser
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 d
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 debug
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 decamelize
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 deep-eql
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 deep-is
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 del
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 diff
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 doctrine
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 eachr
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 editions
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 error-ex
drwxrwxr-x 15 ziyaddin ziyaddin 4,0K Mar 28 22:18 es5-ext
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 es6-iterator
drwxrwxr-x  5 ziyaddin ziyaddin 4,0K Mar 28 22:18 es6-map
drwxrwxr-x  6 ziyaddin ziyaddin 4,0K Mar 28 22:18 es6-set
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 es6-symbol
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 es6-weak-map
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 escape-string-regexp
drwxrwxr-x  6 ziyaddin ziyaddin 4,0K Mar 28 22:18 escope
drwxrwxr-x  7 ziyaddin ziyaddin 4,0K Mar 28 22:18 eslint
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 espree
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 esprima
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 esquery
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 esrecurse
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 estraverse
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 esutils
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 event-emitter
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 exit-hook
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 extract-opts
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 fast-levenshtein
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 figures
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 file-entry-cache
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 find-up
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 flat-cache
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 fs.realpath
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 generate-function
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 generate-object-property
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 get-caller-file
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 glob
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 globals
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 globby
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 graceful-fs
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 graceful-readlink
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 growl
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 has-ansi
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 has-flag
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 hosted-git-info
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 ignore
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 imurmurhash
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 inflight
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 inherits
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 inquirer
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 interpret
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 invert-kv
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 isarray
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-arrayish
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-builtin-module
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-fullwidth-code-point
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-my-json-valid
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-path-cwd
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-path-in-cwd
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-path-inside
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-property
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-resolvable
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 is-utf8
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 json3
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 jsonify
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 jsonpointer
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 json-stable-stringify
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 js-tokens
drwxrwxr-x  5 ziyaddin ziyaddin 4,0K Mar 28 22:18 js-yaml
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lcid
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 levn
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 load-json-file
drwxrwxr-x  3 ziyaddin ziyaddin  20K Mar 28 22:18 lodash
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash._baseassign
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash._basecopy
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash._basecreate
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash.create
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash._getnative
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash.isarguments
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash.isarray
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash._isiterateecall
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 lodash.keys
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 minimatch
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 minimist
drwxrwxr-x  6 ziyaddin ziyaddin 4,0K Mar 28 22:18 mkdirp
drwxrwxr-x  6 ziyaddin ziyaddin 4,0K Mar 28 22:18 mocha
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 ms
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 mute-stream
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 natural-compare
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 normalize-package-data
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 number-is-nan
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 object-assign
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 once
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 onetime
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 optimist
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 optionator
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 os-homedir
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 os-locale
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 parse-json
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 path-exists
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 path-is-absolute
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 path-is-inside
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 path-parse
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 path-type
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 pify
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 pinkie
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 pinkie-promise
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 pluralize
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 prelude-ls
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 process-nextick-args
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 progress
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 readable-stream
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 readline2
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 read-pkg
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 read-pkg-up
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 rechoir
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 require-directory
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 requirefresh
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 require-main-filename
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 require-uncached
drwxrwxr-x  5 ziyaddin ziyaddin 4,0K Mar 28 22:18 resolve
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 resolve-from
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 restore-cursor
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 rimraf
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 run-async
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 rx-lite
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 safefs
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 semver
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 set-blocking
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 shelljs
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 slice-ansi
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 spdx-correct
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 spdx-expression-parse
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 spdx-license-ids
drwxrwxr-x  6 ziyaddin ziyaddin 4,0K Mar 28 22:18 sprintf-js
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 string_decoder
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 string-width
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 strip-ansi
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 strip-bom
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 strip-json-comments
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 supports-color
drwxrwxr-x  5 ziyaddin ziyaddin 4,0K Mar 28 22:18 table
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 text-table
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 through
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 tryit
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 type-check
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 typechecker
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 typedarray
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 type-detect
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 user-home
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 util-deprecate
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 validate-npm-package-license
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 which-module
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 wordwrap
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 wrap-ansi
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 wrappy
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 write
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 xtend
drwxrwxr-x  2 ziyaddin ziyaddin 4,0K Mar 28 22:18 y18n
drwxrwxr-x  4 ziyaddin ziyaddin 4,0K Mar 28 22:18 yargs
drwxrwxr-x  3 ziyaddin ziyaddin 4,0K Mar 28 22:18 yargs-parser
```

**Comment by liuderchi** [comment]
@ziyaddin How did you open Atom? Was it in Dev mode?
( if you are opening Atom in Dev mode, Atom will load packages from `~/.atom/dev/packages/*`
rather than `~/.atom/packages/*` )

Detailed info of reproducing this behavior is welcomed.

**Comment by ziyaddin** [comment]
@liuderchi I have been using Atom in non-Dev mode. How can I run it in Dev mode and in the same time load `atom-i18n` package in Dev mode?

**Comment by liuderchi** [comment]
`apm link -d` links to `~/.atom/dev/packages/*` which is for dev mode

@ziyaddin it's fine to run in non-Dev mode. I was just trying to eliminate some possible errors.

Would you like to remove all related folders (directory link, cloned repo) 
and restart from git clone of latest commits of this repo?

**Comment by ziyaddin** [comment]
@liuderchi I did all instructions again. Still the same result.

**Comment by liuderchi** [comment]
@ziyaddin did you try install it inside atom?

also please provide your atom version via `atom -v` or `atom-beta -v`

**Comment by ziyaddin** [comment]
@liuderchi `atom -v` returns `1.4.0`

**Comment by ziyaddin** [comment]
I tried installing it inside atom, but the same result.

**Comment by ziyaddin** [comment]
@liuderchi now I solved the problem. The problem was the version which I was using. Updated to `1.15.0`.

Thanks for help!

**Comment by liuderchi** [comment]
@ziyaddin Thanks for your help.
I would update Atom version requirement in `package.json` to be `v1.15.0`
